### ISSUE TITLE
July Plan

### ISSUE THREAD

**Issue by BlowaterNostr** [BlowaterNostr/blowater#1]
July is the first month after we Open Sourced Blowater. It’s a vital month for us to deliver a better application to our community.

To define “better”, we consider 3 areas:
1. Zap Integration
#7 (X)
2. DM features
a. #8 
b. #4 
c. #2 
d. #5
e. #14
3. Generally Useful Features
a. #54  
5. #6
a. #9 
b. #10 

- #54 

**[Nostr Discussion](https://nostr.band/note1v9mjdqvy0kds96hyr958r0e3gn26gu6cdsy9ul835cjv8t3qv3kqc3pgze)**

**Comment by pqingshuang** [comment]
can we add one more plan:
make https link clickable

**Comment by BlowaterNostr** [comment]
@pqingshuang we can absolutely do it!

**Comment by BlowaterNostr** [comment]
@pqingshuang #54 here you go!
