### ISSUE TITLE
[0.5] Send message with cmd + enter

### ISSUE THREAD

**Issue by dtonon** [BlowaterNostr/blowater#103]
As per the subject it would improve the UX to enable sending a message with this common keyboard shortcut.

**Comment by BlowaterNostr** [comment]
@dtonon ctrl+enter is supported on Windows, Linux and Mac. It's just cmd+enter on Mac that's left

**Comment by dtonon** [comment]
I'm sorry, I'm so used to `cmd` that I thought the function was not implemented at all, without testing it!

**Comment by dtonon** [comment]
Ok, subject doesn't support markdown :D

**Comment by BlowaterNostr** [comment]
@dtonon Don't worry, Will implement `cmd` as well. I'm using a Mac too.

**Comment by BlowaterNostr** [comment]
@dtonon We will do it next week.
