### ISSUE TITLE
bug: the npub didnt go top to contact list after i send the msg

### ISSUE THREAD

**Issue by pqingshuang** [BlowaterNostr/blowater#19]
![image](https://github.com/BlowaterNostr/blowater/assets/26760878/07dbed7e-97eb-4507-ad27-fd622e1c0423)

**Comment by BlowaterNostr** [comment]
@pqingshuang this is not a bug. The sorting algorithm uses the time of both the last send message and last received message. Because `nosrt.ts copilot` does not reply to you, the sorting is not affected much.

**Comment by pqingshuang** [comment]
feature request!
pop it up!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by BlowaterNostr** [comment]
@pqingshuang the current algorithm is:
assuming the 
last send event has time 10
last received event has time 11
the sort score for this event is 21.

So in your case,
you just send a contact an event, the time is 15. But the contact never responded, so the last received time might be 2 for example. The sort score is 15+2=17, < 21

so it's not at the top.

This algorithm can simulate engagement frequency between you and the contact which I find it more intuitive than just the last message alone.

What if 10 users send msgs to you and you never reply? Do I have to pop them up?
