### ISSUE TITLE
Cannot add to relay list

### ISSUE THREAD

**Issue by badonyx** [BlowaterNostr/blowater#234]
When I go to settings and add relays I cannot go back to the main chat tab, and if I reload the page it simply logs me out and loses my settings.

**Comment by BlowaterNostr** [comment]
@badonyx What is your npub?

**Comment by BlowaterNostr** [comment]
@badonyx Can you have a more detailed description to help us? Screenshots?

**Comment by shaibearary** [comment]
need more details, i  follow the process described but its fine

**Comment by badonyx** [comment]
It works now since support for Alby was fixed. Thanks.
