### ISSUE TITLE
JSON parsing error resulting in white screen

### ISSUE THREAD

**Issue by staab** [BlowaterNostr/blowater#31]
![Screenshot 2023-07-06 at 8 45 49 AM](https://github.com/BlowaterNostr/blowater/assets/2494842/d3852f81-ef2f-4b57-b24e-a14803d96acb)

**Comment by BlowaterNostr** [comment]
@staab Good catch, will fix

**Comment by BlowaterNostr** [comment]
@staab 
<img width="749" alt="image" src="https://github.com/BlowaterNostr/blowater/assets/127284497/896a38db-bcbd-47c4-a8fd-52fd9e311f5b">
In the source code I even noted it since the ever beginning LOL

**Comment by BlowaterNostr** [comment]
@staab fixed in https://github.com/BlowaterNostr/blowater/commit/910521ed74c799dc7c64ccf36e2b2e7201b93762#diff-969646a6c25b905e84fcf387e389e46a088e19b081079d7de495619f0b4b5eae
