### ISSUE TITLE
Local PIN should be hidden when NIP-07 extension is active

### ISSUE THREAD

**Issue by dtonon** [BlowaterNostr/blowater#375]
Currently the app shows the PIN interface also when the user is logged in via NIP-07 extension, but it is not functional, it allows whatever PIN the user enter.

**Comment by BlowaterNostr** [comment]
NIP07 is not implementing NIP-44 at the moment. I plan to disable it for now. Otherwise it breaks all DMs.

**Comment by BlowaterNostr** [comment]
- #377
