### ISSUE TITLE
User is locked out if he does not set a PIN

### ISSUE THREAD

**Issue by dtonon** [BlowaterNostr/blowater#376]
Currently if the user creates a new nsec (or inputs one) and leaves the app or refreshes the page in the creation PIN step, he then remains locked out.
A first solution might be to request the PIN again, but this means that in the meantime the nsec is stored in plain text.
A second solution is to completely reset the session and let the user start from scratch.

**Comment by BlowaterNostr** [comment]
Will do the second solution

**Comment by BlowaterNostr** [comment]
#373
