### ISSUE TITLE
[BUG] Pic missing in a normal conversation

### ISSUE THREAD

**Issue by LiuJiazheng** [BlowaterNostr/blowater#398]
Not sure which NIP proposal is but when a pic is sent from local disk, the pic binary is 'missing', meaning that it is not showing up from sender's side. Not sure receiver side would see this or not.

I have sent pic to creator Blowater and would like to know if he/she sees this.

**Comment by BlowaterNostr** [comment]
Can you attach screen shots or console logs if it's reproducible?

One explaination is that after NIP-44 upgrade, every encrypted data is limited to 64K which is easily smaller than most images.

The old NIP-4 encryption does not have this limitation.

embedding binaries into JSON is a bad practice anyway. I am thinking about using a dedicated image server.
