### ISSUE TITLE
Reply in both kind-1 and kind-4

### ISSUE THREAD

**Issue by BlowaterNostr** [BlowaterNostr/blowater#403]
Discord style reply
<img width="296" alt="image" src="https://github.com/BlowaterNostr/blowater/assets/127284497/4832a99c-c464-401b-939e-7507e35cb70b">

**Comment by BlowaterNostr** [comment]
You are likely to divide this task into many smaller tasks

**Comment by bob2402** [comment]
- [ ] Show the original message being replied to in the reply message
- [ ] Choose a message from someone to respond to
- [ ] Indicate the status of the response on the editor
- [ ] Send reply

**Comment by BlowaterNostr** [comment]
let's deal with kind-4 when we figure out a better scrolling
