### ISSUE TITLE
Make Profile Card Clickable

### ISSUE THREAD

**Issue by BlowaterNostr** [BlowaterNostr/blowater#42]
This week we introduced Profile Card
<img width="513" alt="image" src="https://github.com/BlowaterNostr/blowater/assets/127284497/9defa17c-4c77-4560-823c-4bd520b6212d">
and should make it clickable to show detailed profile.

**Comment by karnagebitcoin** [comment]
Test

**Comment by foodstr** [comment]
Nice

**Comment by GuandeLi** [comment]
let's work it together

**Comment by foodstr** [comment]
Let's work on it together!

**Comment by BlowaterNostr** [comment]
@foodstr can we get it done this weekend?

**Comment by BlowaterNostr** [comment]
#44
