### ISSUE TITLE
PWA: Mobile Notification

### ISSUE THREAD

**Issue by BlowaterNostr** [BlowaterNostr/blowater#48]
per [Sherry's](https://nostr.band/npub1ejxswthae3nkljavznmv66p9ahp4wmj4adux525htmsrff4qym9sz2t3tv) request

**Comment by BlowaterNostr** [comment]
Make https://github.com/BlowaterNostr/blowater/blob/main/UI/notification.ts work on mobile

**Comment by foodstr** [comment]
Right

**Comment by shaibearary** [comment]
you can mention my npub to test nostr connect

**Comment by BlowaterNostr** [comment]
yes npub1ejxswthae3nkljavznmv66p9ahp4wmj4adux525htmsrff4qym9sz2t3tv

**Comment by BlowaterNostr** [comment]
I will not focus on mobile for the next major development cycle
