### ISSUE TITLE
Clickable Note Card

### ISSUE THREAD

**Issue by BlowaterNostr** [BlowaterNostr/blowater#53]
Bounty: 20 USD
Difficulty: Medium
Urgency: Low

similar to #42

**Comment by BlowaterNostr** [comment]
The note can show up in the right panel as well

**Comment by foodstr** [comment]
needs more design

**Comment by foodstr** [comment]
let't do it

**Comment by BlowaterNostr** [comment]
https://github.com/BlowaterNostr/nostr.ts/issues/14
