### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by dergigi** [BlowaterNostr/blowater#88]
- https://choosealicense.com/
- https://choosealicense.com/licenses/
- https://ufal.github.io/public-license-selector/

**Comment by BlowaterNostr** [comment]
Thanks for submitting this issue and I will look deeper into it.

**Comment by BlowaterNostr** [comment]
@dergigi https://github.com/BlowaterNostr/blowater/blob/main/LICENSE
