### ISSUE TITLE
show detail of events

### ISSUE THREAD

**Issue by foodstr** [BlowaterNostr/blowater#90]
- a part of #8 
- https://github.com/BlowaterNostr/blowater/issues/89
- https://github.com/BlowaterNostr/blowater/issues/119
- two format of note id
- two format creator pubkey
- all information exclude content

**Comment by BlowaterNostr** [comment]
We need to create a generic buttong group similar to
<img width="233" alt="image" src="https://github.com/BlowaterNostr/blowater/assets/127284497/65ec4cdd-4593-45af-af03-57ae4c027c55">

**Comment by BlowaterNostr** [comment]
Bounty: 50 USD
Difficulty: Medium
Urgency: High

**Comment by BlowaterNostr** [comment]
#148 step 1 done

**Comment by BlowaterNostr** [comment]
- closed by #150
